// src/components/shader-composer/shader-editor.tsx
"use client";

import { ShaderPreview } from "./shader-preview";
import { LayerStack } from "./layer-stack";
import { PropertyPanel } from "./property-panel";
import { CodeOutput } from "./code-output";

export function ShaderEditor() {
  return (
    <div className="h-screen w-screen flex flex-col bg-background text-foreground overflow-hidden">
        {/* Header */}
        <header className="h-12 border-b border-border flex items-center justify-between px-4 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-6 h-6 rounded bg-gradient-to-br from-violet-500 to-fuchsia-500" />
            <h1 className="font-semibold text-sm">Shader Composer</h1>
          </div>
          <p className="text-xs text-muted-foreground">
            Compose shaders visually, export clean code
          </p>
        </header>

        {/* Main Layout */}
        <div className="flex-1 flex overflow-hidden">
          {/* Left Panel - Layer Stack */}
          <aside className="w-64 border-r border-border flex flex-col shrink-0">
            <LayerStack />
          </aside>

          {/* Center - Preview */}
          <main className="flex-1 flex flex-col min-w-0">
            <div className="flex-1 relative">
              <ShaderPreview />
            </div>
          </main>

          {/* Right Panel - Properties & Code */}
          <aside className="w-80 border-l border-border flex flex-col shrink-0">
            <div className="h-1/2 border-b border-border">
              <PropertyPanel />
            </div>
            <div className="h-1/2">
              <CodeOutput />
            </div>
          </aside>
        </div>
    </div>
  );
}

// src/components/shader-composer/shader-editor.svelte
<script lang="ts">
	import LayerStack from './layer-stack.svelte';
	import ShaderPreview from './shader-preview.svelte';
	import PropertyPanel from './property-panel.svelte';
	import CanvasToolbar from './canvas-toolbar.svelte';
	import EffectsPalette from './effects-palette.svelte';
	import ExportDialog from './export-dialog.svelte';

	let paletteCategory = $state<string | null>(null);
	let exportOpen = $state(false);
</script>

<div class="h-screen w-screen bg-neutral-900 overflow-hidden">
	<div class="flex flex-col h-full w-full px-4 pb-4 overflow-hidden">
		<header class="flex h-[69px] items-center justify-between pl-4 pr-3 py-3 shrink-0">
			<h1
				class="text-[16px] font-medium tracking-[-0.32px] bg-clip-text text-transparent"
				style="background-image: linear-gradient(to bottom, #ffffff, rgba(255,255,255,0.8));"
			>
				Shader Studio
			</h1>
			<button
				type="button"
				onclick={() => (exportOpen = true)}
				class="relative h-9 inline-flex items-center gap-2 px-3 py-3 rounded-lg text-[14px] font-medium text-white border-[0.5px] border-[rgba(255,255,255,0.1)] overflow-hidden cursor-pointer hover:brightness-110 transition"
				style="background-image: linear-gradient(to top, var(--indigo-700), var(--indigo-600));"
			>
				<span class="relative">Export</span>
				<span
					class="pointer-events-none absolute inset-0 rounded-[inherit]"
					style="box-shadow: inset 0 0.5px 1px 0 rgba(255,255,255,0.2);"
				></span>
			</button>
		</header>

		<div class="flex-1 grid grid-cols-[300px_minmax(0,1fr)_300px] gap-4 min-h-0">
			<aside class="glass-panel rounded-3xl overflow-hidden min-h-0">
				<LayerStack />
			</aside>

			<main class="relative p-2 min-h-0">
				<div class="absolute inset-2 rounded-3xl overflow-hidden">
					<ShaderPreview />
				</div>

				{#if paletteCategory}
					<EffectsPalette
						category={paletteCategory}
						onClose={() => (paletteCategory = null)}
					/>
				{/if}

				<CanvasToolbar
					selected={paletteCategory}
					onSelect={(c) => (paletteCategory = paletteCategory === c ? null : c)}
				/>
			</main>

			<aside class="glass-panel rounded-3xl overflow-hidden min-h-0">
				<PropertyPanel />
			</aside>
		</div>
	</div>

	<ExportDialog bind:open={exportOpen} />
</div>
